version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7  # Utilisation d'une version antérieure de Python
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests with Pytest
          command: |
            pytest --junitxml=pytest-results.xml
      - store_test_results:
          path: pytest-results.xml
      - store_artifacts:
          path:
            - pytest-results.xml

workflows:
  version: 2
  example:
    jobs:
      - test
