version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.9  # Utilisation d'une image Python
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt  # Assurez-vous que pytest est dans requirements.txt
      - run:
          name: Run tests with Pytest
          command: |
            pytest --junitxml=pytest-results.xml  # Génère un rapport XML pour les résultats des tests
      - store_test_results:
          path: pytest-results.xml  # Stocke les résultats des tests pour CircleCI
      - store_artifacts:
          path:
            - pytest-results.xml  # Stocke le rapport XML comme artefact

workflows:
  version: 2
  example:
    jobs:
      - test
