version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo "Running tests"
workflows:
  version: 2
  example:
    jobs:
      - test
