version: 2.1

jobs:
  generate-and-add-config:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Generate and add CircleCI config
          command: |
            chmod +x ./scripts/generate-and-add-config.sh
            ./scripts/generate-and-add-config.sh

workflows:
  version: 2
  example:
    jobs:
      - generate-and-add-config
